[package]
name = "secret-box"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
slint = "1.12.0"
rand = "0.9.2"
rusqlite = { version = "0.38.0", features = ["bundled-sqlcipher-vendored-openssl"] }

[build-dependencies]
slint-build = "1.12.0"
windows_exe_info = "0.5.2"